export const helpDeskData = [
    {
        title: "Central Helpdesk",
        desc: "Contact the central help desk if you want to know how we can help you during this pandemic",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/Centralhelpdesk.png",
        button: "Ask for help",
        route: "central-help-desk",
    },
    {
        title: "Blood and Plasma",
        desc: "If you need Blood/ Plasma we will help find contacts and people willing to donate and connect them with you",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/Blood2.png",
        button: "Ask for help",
        route: "blood-and-plasma",
    },
    {
        title: "Hospital Admission",
        desc: "Hospital bed availability is one of the concerning issues right now and we can help you get verified information about the availability",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/Hospital2.png",
        button: "Ask for help",
        route: "hospital-admission",
    },
    {
        title: "Oxygen Bed and Ventilator arrangement",
        desc: "Critical cases might need Oxygen beds and ventilator arrangements and we can help you get correct information and contact details for the same",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/oxygen2.png",
        button: "Ask for help",
        route: "o2-bed-and-ventilator",
    },
    {
        title: "Medicines",
        desc: "We will help you find verified resources for required medecines and also help get them delivered to you if you can't go out due to quarantine or such reasons",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/medicines2.png",
        button: "Ask for help",
        route: "medicines",
    },
    {
        title: "Lab Testing Facility",
        desc: "If you need verified information of the pathology labs and which tests are available in which areas, we will try to provide all the information that you'll need to contact the correct lab",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/lab_test2.png",
        button: "Ask for help",
        route: "lab-testing",
    },
    {
        title: "Moral Support",
        desc: "Hello world",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/moral_support2.png",
        button: "Ask for help",
        route: "moral-support",
    },
    {
        title: "Vaccination",
        desc: "Hello world",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/vaccine2.png",
        button: "Ask for help",
        route: "vaccination",
    },
    {
        title: "Doctors for Suggestions",
        desc: "Hello world",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/Doctor_sugg2.png",
        button: "Ask for help",
        route: "doctors-for-suggestion",
    },
    {
        title: "Food Availability for the needy",
        desc: "We will help you find verified resources for food necessities and also help get the food delivered to you if you can't go out due to quarantine or such reasons",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/food_del2.jpg",
        button: "Ask for help",
        route: "food",
    },
    {
        title: "Post Covid Communication",
        desc: "Hello world",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/post_covid2.png",
        button: "Ask for help",
        route: "post-covid-communication",
    },
    {
        title: "Technical Support",
        desc: "Hello world",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/TechnicalSupport.png",
        button: "Ask for help",
        route: "technical-support",
    },
];
