export const helpDeskData = [
    {
        title: "Central Helpdesk",
        desc: "Contact the central help desk if you want to know how we can help you during this pandemic",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/Centralhelpdesk.webp",
        button: "Ask for help",
        route: "central-help-desk",
    },
    {
        title: "Blood",
        desc: "If you need Blood, we will help find contacts and people willing to donate and connect them with you",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/Blood2.webp",
        button: "Ask for help",
        route: "blood",
    },
    {
        title: "Hospital Admission",
        desc: "Hospital bed availability is one of the concerning issues right now and we can help you get verified information about the availability",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/Hospital2.webp",
        button: "Ask for help",
        route: "hospital-admission",
    },
    {
        title: "Oxygen Bed and Ventilator arrangement",
        desc: "Critical cases might need Oxygen beds and ventilator arrangements and we can help you get correct information and contact details for the same",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/oxygen2.webp",
        button: "Ask for help",
        route: "o2-bed-and-ventilator",
    },
    {
        title: "Medicines",
        desc: "We will help you find verified resources for required medecines and also help get them delivered to you if you can't go out due to quarantine or such reasons",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/medicines2.webp",
        button: "Ask for help",
        route: "medicines",
    },
    {
        title: "Lab Testing Facility",
        desc: "If you need verified information of the pathology labs and which tests are available in which areas, we will try to provide all the information that you'll need to contact the correct lab",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/lab_test2.webp",
        button: "Ask for help",
        route: "lab-testing",
    },
    {
        title: "Moral Support",
        desc: "Mental health should also be a priority in such times of pandemic and we are here to help you in moral support if you need us",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/moral_support2.webp",
        button: "Ask for help",
        route: "moral-support",
    },
    {
        title: "Vaccination",
        desc: "Vaccination against COVID-19 is necessary and if you have any doubts regarding the vaccinations, availability, tips and guidelines you can contact us",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/vaccine2.webp",
        button: "Ask for help",
        route: "vaccination",
    },
    {
        title: "Doctors for Suggestions",
        desc: "We will try and help you get doctor's suggestions if you are facing issues due to the pandemic situation",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/Doctor_sugg2.webp",
        button: "Ask for help",
        route: "doctors-for-suggestion",
    },
    {
        title: "Food Availability for the needy",
        desc: "We will help you find verified resources for food necessities and also help get the food delivered to you if you can't go out due to quarantine or such reasons",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/food_del2.webp",
        button: "Ask for help",
        route: "food",
    },
    {
        title: "Post Covid Communication",
        desc: "You can contact us regarding any issues, suggestions, feedbacks, and/or experiences of after recovering from COVID-19",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/post_covid2.webp",
        button: "Ask for help",
        route: "post-covid-communication",
    },
    {
        title: "Technical Support",
        desc: "Various things are available online due to the lockdown and if you need any technical assistance related to COVID-19 facilities, we are here to help",
        img: "https://raw.githubusercontent.com/devscollab/pcet-covid-task-force/main/src/assets/TechnicalSupport.webp",
        button: "Ask for help",
        route: "technical-support",
    },
];
