
export const leftItems = [
    "Blood",
    "Hospital Admission",
    "Oxygen Bed and Ventilator arrangement",
    "Medicines",
    "Lab Testing Facility",
    "Moral Support",
    "Vaccination",
    "Doctors for Suggestions",
    "Food Availability for the needy",
    "Post Covid Communication",
    "Volunteers",
];


export const Data1 = {
    "Blood":  [
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            },
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            },
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            },
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            },
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            }
        ],
        "Hospital Admission":  [
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    contactNumber: "9999999999",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            },
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    contactNumber: "9999999999",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            },
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    contactNumber: "9999999999",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            },
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    contactNumber: "9999999999",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            },
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    contactNumber: "9999999999",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            }
        ],
        "Oxygen Bed and Ventilator arrangement":  [
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    contactNumber: "9999999999",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            }
        ],
        "Medicines":  [
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    contactNumber: "9999999999",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            }
        ],
        "Volunteers":  [
            {
                requestType: "blood",
                requestObject: {
                    patientName: "Test User",
                    contactNumber: "9999999999",
                    age: "21",
                    bloodGroup: "O+ve",
                    healthCondition: "COVID +ve",
                    requiredBy: 1621900800000,
                    area: "Ravet",
                    city: "Pune",
                    hospital: "The Ravet Hospital, Ravet",
                    message: "Need blood soon (Test message)",
                },
                userId: "60a68b69ac9b5c0032b24795",
            }
        ],
        
};
